In [1]:
import numpy as np

In [8]:
# Creating 1D, 2D, and 3D numpy arrays
array_1d = np.array([1, 2, 3, 4, 5, 6])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [15]:
# Accessing elements in the array
# 1D array
print('1D access:')
print(array_1d[3])
print(array_1d[1] + array_1d[0])
print()

# 2D array
print('2D access:')
print('Third Element in first row of 2D array: ', array_2d[0, 2])
print('Second Element in second row of 2D array: ', array_2d[1, 1])
print()

# 3D array
print('3D access:')
print(array_3d)
print(array_3d[1, 0, 0])
print()

# negative indexing
print('Negative Indexing:')
print('Last element of 1D array: ', array_1d[-1])
print(array_2d[1, -1])
print(array_3d[1, 1, -1])

1D access:
4
3

2D access:
Third Element in first row of 2D array:  3
Second Element in second row of 2D array:  5

3D access:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
7

Negative Indexing:
Last element of 1D array:  6
6
12


In [24]:
# Slicing Arrays
# array[start:stop] - default start is 0, default stop is length of array
# array[start:stop:step] - default step is 1

Employee_Rating = np.array([1, 4, 3, 5, 6, 8, 9, 10, 12])
print(Employee_Rating[1:7])

# default start and stop
Books = np.array(['Physics', 'DataScience', 'Maths', 'Python', 'Hadopp', 'OOPs', 'Java', 'C++', 'DSA', 'C', 'Networking'])
print(Books[5:]) 
print(Books[:5]) 

# using step
X = np.array([8, 7, 6, 5, 4, 3, 2, 1])
print(X[1:6:3])


# slicing in 2D
Z = np.array([[11, 22, 33, 44, 55], [66, 77, 88, 99, 110]])
print(Z[0, 2:3])

# slicing in 3D
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d[0, 1:, 1:])

# negative slicing
arr = np.array([13, 34, 58, 69, 44, 56, 37, 24])
print(arr[:-1])

[4 3 5 6 8 9]
['OOPs' 'Java' 'C++' 'DSA' 'C' 'Networking']
['Physics' 'DataScience' 'Maths' 'Python' 'Hadopp']
[7 4]
[33]
[[5 6]]
[13 34 58 69 44 56 37]


In [25]:
# assignment
# 1
arr1D = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# 2 
arr2D = np.array(
    [
        [1,  2,  3,  4], 
        [5,  6,  7,  8], 
        [9, 10, 11, 12]
    ]
)

# 3
arr3D = np.array(
    [
        [
            [1, 2, 3], 
            [4, 5, 6]
        ], 
        [
            [7, 8, 9], 
            [10, 11, 12]
        ]
    ]
)

# 4
print('Index 3 of arr1D: ', arr1D[3])
print('Sliced arr1D from index 2 to 6: ', arr1D[2:6])
print()

# print('Index 3 of arr1D: ', arr1D[3])
# print('Sliced arr1D from index 2 to 6: ', arr1D[2:6])

Index 3 of arr1D:  40
Sliced arr1D from index 2 to 6:  [30 40 50 60]

